services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
        # bind mount - 
        # starts with a . or /
        # relative or abs path
    ports:
      - 5051:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
        # named volume
        # doesn't start w . or /
        # docker manages the data location for you
        # recommended way for data storage
        # you can see where they're located with `docker volumes ls`
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
